site_name: Siddhi Execution Unitconversion
site_description: Siddhi Execution Unitconversion Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-execution-unitconversion/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-Execution-Unitconversion
repo_url: https://github.com/wso2-extensions/siddhi-execution-unitconversion
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: 'material'
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
markdown_extensions:
  - admonition
  - toc(permalink=true)
  - codehilite(guess_lang=false)
pages:
- Welcome: index.md
- API Docs:
  - 1.0.15: api/1.0.15.md
  - 1.0.14: api/1.0.14.md
  - 1.0.13: api/1.0.13.md
  - 1.0.12: api/1.0.12.md
  - 1.0.11: api/1.0.11.md
  - 1.0.10: api/1.0.10.md
  - 1.0.9: api/1.0.9.md
  - 1.0.8: api/1.0.8.md
  - 1.0.7: api/1.0.7.md
  - 1.0.6: api/1.0.6.md
  - 1.0.5: api/1.0.5.md
  - latest: api/latest.md
- License: license.md
